//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenX.Cli.Core.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenX.Cli.Core.Commands.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start genx by attaching a debugger..
        /// </summary>
        internal static string DebugDescription {
            get {
                return ResourceManager.GetString("DebugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving metadata file {0}: {1}.
        /// </summary>
        internal static string ErrorSavingMetadataFile {
            get {
                return ResourceManager.GetString("ErrorSavingMetadataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Source Code using an Xml metadata generated file..
        /// </summary>
        internal static string GenerateCommandDescription {
            get {
                return ResourceManager.GetString("GenerateCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Xml metadata using a dotnet Assembly..
        /// </summary>
        internal static string GenerateDotnetDescription {
            get {
                return ResourceManager.GetString("GenerateDotnetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Xml metadata using an Oldb connection string..
        /// </summary>
        internal static string GenerateOledbDescription {
            get {
                return ResourceManager.GetString("GenerateOledbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Xml metadata using Sql Server Management Objects..
        /// </summary>
        internal static string GenerateSqlDescription {
            get {
                return ResourceManager.GetString("GenerateSqlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate command expects a connection string and output filename for the metadata..
        /// </summary>
        internal static string HelpMetadataDbParameters {
            get {
                return ResourceManager.GetString("HelpMetadataDbParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate command expects an assembly filename and output filename for the metadata..
        /// </summary>
        internal static string HelpMetadataDotnetParameters {
            get {
                return ResourceManager.GetString("HelpMetadataDotnetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays usage / help text..
        /// </summary>
        internal static string HelpOptionDescription {
            get {
                return ResourceManager.GetString("HelpOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Xml metadata from one of the metadata providers..
        /// </summary>
        internal static string MetadataCommandDescription {
            get {
                return ResourceManager.GetString("MetadataCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata file {0} does not exist..
        /// </summary>
        internal static string MetadataFileDoesNotExist {
            get {
                return ResourceManager.GetString("MetadataFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output is not written to StdOut, only StdErr..
        /// </summary>
        internal static string NoLoggingDescription {
            get {
                return ResourceManager.GetString("NoLoggingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs genx without displaying the logo/startup banner..
        /// </summary>
        internal static string NoLogoDescription {
            get {
                return ResourceManager.GetString("NoLogoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --outputextension option is required..
        /// </summary>
        internal static string OutputExtensionRequired {
            get {
                return ResourceManager.GetString("OutputExtensionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser warning: Discarded unexpected token..
        /// </summary>
        internal static string ParserDiscardedUnexpectedToken {
            get {
                return ResourceManager.GetString("ParserDiscardedUnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser error: Expected metadata-options..
        /// </summary>
        internal static string ParserExpectedMetadataOption {
            get {
                return ResourceManager.GetString("ParserExpectedMetadataOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected [xslt-options].
        /// </summary>
        internal static string ParserExpectedXsltOption {
            get {
                return ResourceManager.GetString("ParserExpectedXsltOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected --xsltparam &lt;paramname:paramvalue&gt;.
        /// </summary>
        internal static string ParserExpectedXsltParam {
            get {
                return ResourceManager.GetString("ParserExpectedXsltParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup options.
        /// </summary>
        internal static string StartupOptionsDescription {
            get {
                return ResourceManager.GetString("StartupOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xslt file {0} does not exist..
        /// </summary>
        internal static string TransformFileDoesNotExist {
            get {
                return ResourceManager.GetString("TransformFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs genx with detailed logging written to StdOut..
        /// </summary>
        internal static string VerboseDescription {
            get {
                return ResourceManager.GetString("VerboseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the version..
        /// </summary>
        internal static string VersionDescription {
            get {
                return ResourceManager.GetString("VersionDescription", resourceCulture);
            }
        }
    }
}
