//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenX.Cli.Infrastructure.SqlClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenX.Cli.Infrastructure.SqlClient.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining unique entities....
        /// </summary>
        internal static string DeterminingUniqueEntities {
            get {
                return ResourceManager.GetString("DeterminingUniqueEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining unique schemas....
        /// </summary>
        internal static string DeterminingUniqueSchemas {
            get {
                return ResourceManager.GetString("DeterminingUniqueSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open SqlClient connection &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedToOpenSqlClientConnection {
            get {
                return ResourceManager.GetString("FailedToOpenSqlClientConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening database with connection string: {0}....
        /// </summary>
        internal static string OpeningDatabaseWithConnectionString {
            get {
                return ResourceManager.GetString("OpeningDatabaseWithConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Columns for entity {0}....
        /// </summary>
        internal static string ReadingColumns {
            get {
                return ResourceManager.GetString("ReadingColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading entity [{0}].[{1}]....
        /// </summary>
        internal static string ReadingEntity {
            get {
                return ResourceManager.GetString("ReadingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Foreign Keys for entity [{0}]....
        /// </summary>
        internal static string ReadingForeignKeys {
            get {
                return ResourceManager.GetString("ReadingForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Primary Keys for entity [{0}]....
        /// </summary>
        internal static string ReadingPrimaryKeys {
            get {
                return ResourceManager.GetString("ReadingPrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading schema [{0}]....
        /// </summary>
        internal static string ReadingSchema {
            get {
                return ResourceManager.GetString("ReadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading schema columns....
        /// </summary>
        internal static string ReadingSchemaColumns {
            get {
                return ResourceManager.GetString("ReadingSchemaColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading SqlClient metadata....
        /// </summary>
        internal static string ReadingSqlClientMetadata {
            get {
                return ResourceManager.GetString("ReadingSqlClientMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened database connection..
        /// </summary>
        internal static string SucessfullyOpenedConnection {
            get {
                return ResourceManager.GetString("SucessfullyOpenedConnection", resourceCulture);
            }
        }
    }
}
