//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenX.Cli.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenX.Cli.Infrastructure.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load metadata file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorLoadingMetadataDocument {
            get {
                return ResourceManager.GetString("ErrorLoadingMetadataDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Xslt file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorLoadingTransformDocument {
            get {
                return ResourceManager.GetString("ErrorLoadingTransformDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating output file: &apos;{0}&apos;.
        /// </summary>
        internal static string GeneratingOutputfile {
            get {
                return ResourceManager.GetString("GeneratingOutputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading metadata file: &apos;{0}&apos;....
        /// </summary>
        internal static string LoadingMetadataFile {
            get {
                return ResourceManager.GetString("LoadingMetadataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Xslt file: &apos;{0}&apos;....
        /// </summary>
        internal static string LoadingXsltFile {
            get {
                return ResourceManager.GetString("LoadingXsltFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter: &apos;{0}&apos; = &apos;{1}&apos;.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforming entity &apos;{0}&apos;
        ///    Xslt Path: {1}
        ///    Metadata Path: {2}
        ///    Output Directory: {3}
        ///    Output Filename: {4}.
        /// </summary>
        internal static string TransformConfig {
            get {
                return ResourceManager.GetString("TransformConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing column {0}....
        /// </summary>
        internal static string WritingMetadataColumn {
            get {
                return ResourceManager.GetString("WritingMetadataColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Db Model to Xml metadata....
        /// </summary>
        internal static string WritingMetadataDbModelToXml {
            get {
                return ResourceManager.GetString("WritingMetadataDbModelToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing entity {0}....
        /// </summary>
        internal static string WritingMetadataEntity {
            get {
                return ResourceManager.GetString("WritingMetadataEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Foreign Keys....
        /// </summary>
        internal static string WritingMetadataForeignKeys {
            get {
                return ResourceManager.GetString("WritingMetadataForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Relationships....
        /// </summary>
        internal static string WritingMetadataRelationships {
            get {
                return ResourceManager.GetString("WritingMetadataRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xslt Parameters:.
        /// </summary>
        internal static string XsltParameters {
            get {
                return ResourceManager.GetString("XsltParameters", resourceCulture);
            }
        }
    }
}
