//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenX.Cli.Infrastructure.Dotnet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenX.Cli.Infrastructure.Dotnet.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying namespace wildcard match: {0}.
        /// </summary>
        internal static string ApplyingWildcardMatch {
            get {
                return ResourceManager.GetString("ApplyingWildcardMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load a file that is not a dotnet Assembly: {0}.
        /// </summary>
        internal static string BadImage {
            get {
                return ResourceManager.GetString("BadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Assembly &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string FailedToLoadAssembly {
            get {
                return ResourceManager.GetString("FailedToLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering on namespace: {0}.
        /// </summary>
        internal static string FilteringOnNamespace {
            get {
                return ResourceManager.GetString("FilteringOnNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Assembly &apos;{0}&apos;....
        /// </summary>
        internal static string LoadingAssembly {
            get {
                return ResourceManager.GetString("LoadingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Assembly Type {0}....
        /// </summary>
        internal static string ReadingAssemblyType {
            get {
                return ResourceManager.GetString("ReadingAssemblyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning all Assembly Types.
        /// </summary>
        internal static string ReturningAllAssemblyTypes {
            get {
                return ResourceManager.GetString("ReturningAllAssemblyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Ctor {0}....
        /// </summary>
        internal static string WritingConstructor {
            get {
                return ResourceManager.GetString("WritingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Assembly Model to Xml metadata....
        /// </summary>
        internal static string WritingMetadataAssemblyModelToXml {
            get {
                return ResourceManager.GetString("WritingMetadataAssemblyModelToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Ctor {0}....
        /// </summary>
        internal static string WritingMetadataConstructor {
            get {
                return ResourceManager.GetString("WritingMetadataConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Method {0}....
        /// </summary>
        internal static string WritingMetadataMethod {
            get {
                return ResourceManager.GetString("WritingMetadataMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Parameter {0}....
        /// </summary>
        internal static string WritingMetadataParameter {
            get {
                return ResourceManager.GetString("WritingMetadataParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Property {0}....
        /// </summary>
        internal static string WritingMetadataProperty {
            get {
                return ResourceManager.GetString("WritingMetadataProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Type {0}....
        /// </summary>
        internal static string WritingMetadataType {
            get {
                return ResourceManager.GetString("WritingMetadataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Method {0}....
        /// </summary>
        internal static string WritingMethod {
            get {
                return ResourceManager.GetString("WritingMethod", resourceCulture);
            }
        }
    }
}
